core:
    locale: en
    flushInterval: 10
    cacheSize: 20000
    showNotices: true
    showMyNotices: true
    opIsLWCAdmin: true
    precache: -1
    disableHistory: true
    groupPrefix: group.
    updateNotifier: true
    factionCheck: false
protections:
    denyRedstone: false
    autoRegister: false
    ignoreBlockDestruction: false
    ignoreLeftClick: false
    ignoreRightClick: false
    blocks:
        chest:
            enabled: true
            autoRegister: false
        brewing_stand:
            enabled: true
            autoRegister: false
        barrel:
            enabled: true
            autoRegister: false
        lectern:
            enabled: true
            autoRegister: false
        smoker:
            enabled: true
            autoRegister: false
        blast_furnace:
            enabled: true
            autoRegister: false
        composter:
            enabled: true
            autoRegister: false
        furnace:
            enabled: true
            autoRegister: false
        dispenser:
            enabled: true
            autoRegister: false
        dropper:
            autoRegister: false
            enabled: true
        oak_sign:
            enabled: true
            autoRegister: false
        spruce_sign:
            enabled: true
            autoRegister: false
        birch_sign:
            enabled: true
            autoRegister: false
        jungle_sign:
            enabled: true
            autoRegister: false
        acacia_sign:
            enabled: true
            autoRegister: false
        dark_oak_sign:
            enabled: true
            autoRegister: false
        oak_door:
            enabled: true
            autoRegister: false
        iron_door:
            enabled: true
            autoRegister: false
        spruce_door:
            enabled: true
            autoRegister: false
        birch_door:
            enabled: true
            autoRegister: false
        jungle_door:
            enabled: true
            autoRegister: false
        acacia_door:
            enabled: true
            autoRegister: false
        oak_trapdoor:
            enabled: true
            autoRegister: false
        dark_oak_trapdoor:
            enabled: true
            autoRegister: false
        birch_trapdoor:
            enabled: true
            autoRegister: false
        spruce_trapdoor:
            enabled: true
            autoRegister: false
        acacia_trapdoor:
            enabled: true
            autoRegister: false
        jungle_trapdoor:
            enabled: true
            autoRegister: false
        warped_trapdoor:
            autoRegister: false
            enabled: true
        crimson_trapdoor:
            autoRegister: false
            enabled: true
        mangrove_trapdoor:
            autoRegister: false
            enabled: true
        cherry_trapdoor:
            autoRegister: false
            enabled: true
        dark_oak_door:
            enabled: true
            autoRegister: false
        warped_door:
            autoRegister: false
            enabled: true
        crimson_door:
            autoRegister: false
            enabled: true
        mangrove_door:
            autoRegister: false
            enabled: true
        cherry_door:
            autoRegister: false
            enabled: true
        iron_trapdoor:
            enabled: true
            autoRegister: false
        trapped_chest:
            autoRegister: false
            enabled: true
        oak_fence_gate:
            autoRegister: false
            enabled: true
        birch_fence_gate:
            autoRegister: false
            enabled: true
        spruce_fence_gate:
            autoRegister: false
            enabled: true
        jungle_fence_gate:
            autoRegister: false
            enabled: true
        acacia_fence_gate:
            autoRegister: false
            enabled: true
        dark_oak_fence_gate:
            autoRegister: false
            enabled: true
        warped_fence_gate:
            autoRegister: false
            enabled: true
        crimson_fence_gate:
            autoRegister: false
            enabled: true
        mangrove_fence_gate:
            autoRegister: false
            enabled: true
        cherry_fence_gate:
            autoRegister: false
            enabled: true
        bamboo_door:
            autoRegister: false
            enabled: true
        bamboo_trapdoor:
            autoRegister: false
            enabled: true
        bamboo_fence_gate:
            autoRegister: false
            enabled: true
        bookshelf:
            autoRegister: false
            enabled: true
        anvil:
            autoRegister: false
            enabled: true
        enchantment_table:
            autoRegister: false
            enabled: true
        cauldron:
            autoRegister: false
            enabled: true
        hopper:
            autoRegister: false
            enabled: true
        pale_oak_door:
            autoRegister: false
            enabled: true
        pale_oak_trapdoor:
            autoRegister: false
            enabled: true
        pale_oak_fence_gate:
            autoRegister: false
            enabled: true
        copper_door:
            autoRegister: false
            enabled: true
        exposed_copper_door:
            autoRegister: false
            enabled: true
        weathered_copper_door:
            autoRegister: false
            enabled: true
        oxidized_copper_door:
            autoRegister: false
            enabled: true
        waxed_copper_door:
            autoRegister: false
            enabled: true
        waxed_exposed_copper_door:
            autoRegister: false
            enabled: true
        waxed_weathered_copper_door:
            autoRegister: false
            enabled: true
        waxed_oxidized_copper_door:
            autoRegister: false
            enabled: true
        copper_trapdoor:
            autoRegister: false
            enabled: true
        exposed_copper_trapdoor:
            autoRegister: false
            enabled: true
        weathered_copper_trapdoor:
            autoRegister: false
            enabled: true
        oxidized_copper_trapdoor:
            autoRegister: false
            enabled: true
        waxed_copper_trapdoor:
            autoRegister: false
            enabled: true
        waxed_exposed_copper_trapdoor:
            autoRegister: false
            enabled: true
        waxed_weathered_copper_trapdoor:
            autoRegister: false
            enabled: true
        waxed_oxidized_copper_trapdoor:
            autoRegister: false
            enabled: true
    ignoreExplosions: false
    quiet: false
    allowEntityBreakDoor: false
    allowEntityInteract: false
    readonly-modify: false
    readonly-remove: false
    denyHoppers: true
modes:
    droptransfer:
        enabled: false
    persist:
        enabled: true
optional:
    onlyProtectWhenOwnerIsOnline: false
    onlyProtectWhenOwnerIsOffline: false
    optOut: false
    exemptBlocks: []
    blacklistedBlocks:
        - '166'
        - '154'
        - hopper
    blacklistedPlayers:
        - plr
    useProtectionLimits: true
    useActionBar: true
    alternativeHopperProtection: false
    useFormattedInfo: true
database:
    adapter: sqlite
    path: plugins/LWC/lwc.db
    host: localhost
    database: lwc
    username: ''
    password: ''
    prefix: lwc_
    ping_interval: 300
    useSSL: false
    allowPublicKeyRetrieval: false
